name: clear_manual_azurecli

on:
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_AZURECLI_CLINF_GL_JOEBSTL }}

    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: azurecli

    - name: Azure CLI clear 1
      uses: azure/CLI@v1
      with:
        azcliversion: 2.46.0
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/Clear.azcli
          $GITHUB_WORKSPACE/Clear.azcli

    - name: Azure CLI clear 2
      uses: azure/CLI@v1
      with:
        azcliversion: 2.46.0
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/Clear.azcli
          $GITHUB_WORKSPACE/Clear.azcli
    
    - name: Azure CLI clear 3
      uses: azure/CLI@v1
      with:
        azcliversion: 2.46.0
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/Clear.azcli
          $GITHUB_WORKSPACE/Clear.azcli