name: deploy_manual_azurecli

on:
  workflow_dispatch:
    inputs:
      numberOfVMs:
        description: 'Define the amount of deployed VMs for the backend (default=2)'
        required: false
        type: number


jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_AZURECLI }}

    - name: Checkout
      uses: actions/checkout@v1
      with:
        ref: azurecli

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: 2.46.0
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/Network.azcli
          $GITHUB_WORKSPACE/Network.azcli ${{ inputs.numberOfVMs }}
          chmod +x $GITHUB_WORKSPACE/VM.azcli
          $GITHUB_WORKSPACE/VM.azcli ${{ inputs.numberOfVMs }}
          chmod +x $GITHUB_WORKSPACE/LoadBalancer.azcli
          $GITHUB_WORKSPACE/LoadBalancer.azcli ${{ inputs.numberOfVMs }}
